---
- name: Download githubcli-archive-keyring.gpg
  become: yes
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'

- name: Get architecture
  become: yes
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: get_architecture

- name: Add gh to apt source list
  become: true
  ansible.builtin.copy:
    content: "deb [arch={{ get_architecture.stdout }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    dest: /etc/apt/sources.list.d/github-cli.list

- name: Run apt update
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install gh
  become: yes
  ansible.builtin.apt:
    name: gh
    state: latest
