---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: ubuntu_focal
    image: ubuntu:focal
  - name: ubuntu_jammy
    image: ubuntu:jammy
  - name: debian_bullseye
    image: debian:bullseye
  - name: debian_bookworm
    image: debian:bookworm
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        gh_config_editor: vim
        gh_config_git_protocol: ssh
        gh_config_prompt: disabled
verifier:
  name: ansible

