---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather the package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto

    - name: Check that git package installed
      ansible.builtin.assert:
        that:
          - "'gh' in ansible_facts.packages"

    - ansible.builtin.command: gh config list
      register: get_gh_config
      changed_when: false

    - debug: var=get_gh_config
    # - name: Check gh configs
    #   ansible.builtin.assert:
    #     that:
    #       - "'core.filemode=false' in get_gh_config.stdout_lines"
    #       - "'core.gitproxy=ssh' in get_gh_config.stdout_lines"
